CREATE DATABASE IF NOT EXISTS biblioteca;

USE biblioteca;

DROP TABLE IF EXISTS libro;

CREATE TABLE libro (
    id_libro INT AUTO_INCREMENT,
    titulo VARCHAR(100),
    autor VARCHAR(100),
    anio_publicacion INT(4),
    genero VARCHAR(100),
    PRIMARY KEY (id_libro)
);

INSERT INTO libro (titulo, autor, anio_publicacion, genero) VALUES
('Cien años de soledad', 'Gabriel García Márquez', 1967, 'Realismo mágico'),
('1984', 'George Orwell', 1949, 'Ciencia ficción'),
('Don Quijote de la Mancha', 'Miguel de Cervantes', 1605, 'Novela'),
('Crimen y castigo', 'Fiódor Dostoyevski', 1866, 'Novela psicológica'),
('Orgullo y prejuicio', 'Jane Austen', 1813, 'Romance'),
('El gran Gatsby', 'F. Scott Fitzgerald', 1925, 'Ficción'),
('Matar a un ruiseñor', 'Harper Lee', 1960, 'Novela'),
('Los miserables', 'Victor Hugo', 1862, 'Drama'),
('Ulises', 'James Joyce', 1922, 'Ficción'),
('Fahrenheit 451', 'Ray Bradbury', 1953, 'Ciencia ficción'),
('La Odisea', 'Homero', -800, 'Épica'),
('El nombre de la rosa', 'Umberto Eco', 1980, 'Misterio'),
('En busca del tiempo perdido', 'Marcel Proust', 1913, 'Ficción'),
('Rayuela', 'Julio Cortázar', 1963, 'Novela experimental'),
('El proceso', 'Franz Kafka', 1925, 'Ficción'),
('El señor de los anillos', 'J.R.R. Tolkien', 1954, 'Fantasía'),
('La divina comedia', 'Dante Alighieri', 1320, 'Poesía'),
('Madame Bovary', 'Gustave Flaubert', 1856, 'Realismo'),
('El extranjero', 'Albert Camus', 1942, 'Existencialismo'),
('Las aventuras de Sherlock Holmes', 'Arthur Conan Doyle', 1892, 'Misterio'),
('Drácula', 'Bram Stoker', 1897, 'Terror'),
('Frankenstein', 'Mary Shelley', 1818, 'Terror'),
('La metamorfosis', 'Franz Kafka', 1915, 'Novela corta'),
('El retrato de Dorian Gray', 'Oscar Wilde', 1890, 'Ficción'),
('Los juegos del hambre', 'Suzanne Collins', 2008, 'Distopía'),
('Dune', 'Frank Herbert', 1965, 'Ciencia ficción'),
('Moby-Dick', 'Herman Melville', 1851, 'Aventura'),
('El código Da Vinci', 'Dan Brown', 2003, 'Misterio'),
('El principito', 'Antoine de Saint-Exupéry', 1943, 'Infantil'),
('El Hobbit', 'J.R.R. Tolkien', 1937, 'Fantasía'),
('It', 'Stephen King', 1986, 'Terror'),
('La carretera', 'Cormac McCarthy', 2006, 'Distopía'),
('El perfume', 'Patrick Süskind', 1985, 'Ficción histórica'),
('Sapiens', 'Yuval Noah Harari', 2011, 'Historia'),
('La isla del tesoro', 'Robert Louis Stevenson', 1883, 'Aventura'),
('El arte de la guerra', 'Sun Tzu', -500, 'Estrategia'),
('Cumbres Borrascosas', 'Emily Brontë', 1847, 'Romance'),
('El castillo', 'Franz Kafka', 1926, 'Ficción'),
('Ensayo sobre la ceguera', 'José Saramago', 1995, 'Ficción'),
('El viejo y el mar', 'Ernest Hemingway', 1952, 'Aventura'),
('Los pilares de la Tierra', 'Ken Follett', 1989, 'Ficción histórica'),
('Anna Karénina', 'León Tolstói', 1877, 'Drama'),
('Las crónicas de Narnia', 'C.S. Lewis', 1950, 'Fantasía'),
('La historia interminable', 'Michael Ende', 1979, 'Fantasía'),
('Memorias de Adriano', 'Marguerite Yourcenar', 1951, 'Ficción histórica'),
('Rebelión en la granja', 'George Orwell', 1945, 'Sátira política'),
('Pedro Páramo', 'Juan Rulfo', 1955, 'Realismo mágico'),
('Los detectives salvajes', 'Roberto Bolaño', 1998, 'Ficción'),
('Trilogía de Nueva York', 'Paul Auster', 1985, 'Misterio'),
('Cien poemas de amor', 'Pablo Neruda', 1959, 'Poesía'),
('Los hombres me explican cosas', 'Rebecca Solnit', 2014, 'Ensayo'),
('El corazón de las tinieblas', 'Joseph Conrad', 1899, 'Novela'),
('La sombra del viento', 'Carlos Ruiz Zafón', 2001, 'Misterio'),
('La tregua', 'Mario Benedetti', 1960, 'Drama'),
('La insoportable levedad del ser', 'Milan Kundera', 1984, 'Filosofía'),
('American Gods', 'Neil Gaiman', 2001, 'Fantasía'),
('Buenos días, tristeza', 'Françoise Sagan', 1954, 'Drama'),
('Siddhartha', 'Hermann Hesse', 1922, 'Filosofía'),
('Yo, robot', 'Isaac Asimov', 1950, 'Ciencia ficción'),
('El sonido y la furia', 'William Faulkner', 1929, 'Ficción'),
('El cuento de la criada', 'Margaret Atwood', 1985, 'Distopía'),
('El Aleph', 'Jorge Luis Borges', 1949, 'Cuentos'),
('El túnel', 'Ernesto Sabato', 1948, 'Psicológico'),
('Solaris', 'Stanisław Lem', 1961, 'Ciencia ficción'),
('Los heraldos negros', 'César Vallejo', 1919, 'Poesía'),
('Harry Potter y la piedra filosofal', 'J.K. Rowling', 1997, 'Fantasía'),
('Las uvas de la ira', 'John Steinbeck', 1939, 'Drama'),
('Bajo la misma estrella', 'John Green', 2012, 'Juvenil'),
('El lobo estepario', 'Hermann Hesse', 1927, 'Existencialismo'),
('Sin noticias de Gurb', 'Eduardo Mendoza', 1991, 'Humor'),
('Los días de la peste', 'Edmundo Paz Soldán', 2017, 'Ficción'),
('La casa de los espíritus', 'Isabel Allende', 1982, 'Realismo mágico'),
('El ruido y la furia', 'William Faulkner', 1929, 'Ficción'),
('Ética para Amador', 'Fernando Savater', 1991, 'Filosofía'),
('Los ejércitos', 'Evelio Rosero', 2007, 'Novela'),
('Las venas abiertas de América Latina', 'Eduardo Galeano', 1971, 'Historia'),
('Mujercitas', 'Louisa May Alcott', 1868, 'Ficción'),
('La vida es sueño', 'Pedro Calderón de la Barca', 1635, 'Teatro'),
('Sobre héroes y tumbas', 'Ernesto Sabato', 1961, 'Ficción'),
('El hombre en busca de sentido', 'Viktor Frankl', 1946, 'Psicología'),
('El guardián entre el centeno', 'J.D. Salinger', 1951, 'Ficción'),
('Las mil y una noches', 'Anónimo', 800, 'Cuentos'),
('La perla', 'John Steinbeck', 1947, 'Ficción'),
('Borges oral', 'Jorge Luis Borges', 1979, 'Ensayo'),
('Los relámpagos de agosto', 'Jorge Ibargüengoitia', 1964, 'Ficción'),
('Hacia rutas salvajes', 'Jon Krakauer', 1996, 'Aventura'),
('La dama de las camelias', 'Alexandre Dumas', 1848, 'Drama');

